python_sources(
    dependencies=[
        # ":config_resources",
        ":statics_files",
        # "python/3rdparty/dependency-injector_4.41.0:reqs",
    ]
)

resources(name="statics_files", sources=["./**/*"])
