[tool.poetry]
name = "stock-radar-app"
version = "0.1.0"
description = ""
authors = ["pecolynx <pecolynx@gmail.com>"]
readme = "README.md"
packages = [{include = "stock_radar_app"}]

[tool.poetry.dependencies]
python = "^3.9,<3.10"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
