---
db:
  url: sqlite:///sample_db.sqlite3
#  url: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
#  username: ${DB_USERNAME}
#  password: ${DB_PASSWORD}
#  host: ${DB_HOST}
#  port: ${DB_PORT}
#  database: ${DB_NAME}

logging:
  level: !ENV ${LOG_LEVEL:INFO}
  format: !ENV ${LOG_FORMAT:PLAIN}
